CREATE TABLE IF NOT EXISTS exchanges (
    id                  BIGINT       NOT NULL AUTO_INCREMENT,
    requester_id        BIGINT       NOT NULL,
    respondent_id       BIGINT       NOT NULL,
    requested_book_id   BIGINT       NOT NULL,
    offered_book_id     BIGINT       NOT NULL,
    status              VARCHAR(20)  NOT NULL DEFAULT 'PENDING',
    message             VARCHAR(300),
    completed_at        DATETIME(6),
    created_at          DATETIME(6)  NOT NULL,
    updated_at          DATETIME(6)  NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_exchanges_requester      FOREIGN KEY (requester_id)      REFERENCES users (id),
    CONSTRAINT fk_exchanges_respondent     FOREIGN KEY (respondent_id)     REFERENCES users (id),
    CONSTRAINT fk_exchanges_requested_book FOREIGN KEY (requested_book_id) REFERENCES books (id),
    CONSTRAINT fk_exchanges_offered_book   FOREIGN KEY (offered_book_id)   REFERENCES books (id),
    INDEX idx_exchanges_requester  (requester_id),
    INDEX idx_exchanges_respondent (respondent_id),
    INDEX idx_exchanges_status     (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
