CREATE TABLE IF NOT EXISTS reading_records (
    id          BIGINT       NOT NULL AUTO_INCREMENT,
    user_id     BIGINT       NOT NULL,
    book_title  VARCHAR(200) NOT NULL,
    author      VARCHAR(100) NOT NULL,
    isbn        VARCHAR(20),
    rating      TINYINT      NOT NULL,
    memo        TEXT,
    image_url   VARCHAR(500),
    cover_color VARCHAR(20)  NOT NULL DEFAULT 'blue',
    is_public   BOOLEAN      NOT NULL DEFAULT TRUE,
    read_at     DATE         NOT NULL,
    created_at  DATETIME(6)  NOT NULL,
    updated_at  DATETIME(6)  NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_reading_records_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    INDEX idx_reading_records_user   (user_id),
    INDEX idx_reading_records_public (user_id, is_public),
    INDEX idx_reading_records_read_at (read_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
